services:
  # Backend Service
  - type: web
    name: seva-link-backend
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGING_FACE_TOKEN
        sync: false
      - key: ENABLE_VOICE_RESPONSES
        value: true
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        value: https://seva-link-frontend.onrender.com
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  # Frontend Service (React)
  - type: web
    name: seva-link-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: |
      npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://seva-link-backend.onrender.com
